import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile, appendFile } from 'node:fs/promises';
import path from 'node:path';
import { localDataFixture } from './fixtures/local-data-app.mjs';
import { codexHistoryFixture } from './fixtures/codex-history.mjs';
import { parseCodexTranscript, orientationPart, createChatGPTImport } from '../server/chatgpt-import.mjs';
import { createLocalDataStore } from '../server/data/store.mjs';

test('setup imports exact-folder snapshots once before indexing, shares chat/history/export and resumes through native API', async t => {
  const f = await localDataFixture(); t.after(() => f.close());
  const source = await codexHistoryFixture(f);
  const nativeBefore = await readFile(f.nativeFile), dbBefore = await readFile(source.database);
  const folders = await f.api('projects/folders?' + new URLSearchParams({ directory: f.root }));
  assert.ok(folders.folders.some(row => row.path === f.directory));
  const preview = await f.api('projects/import-preview', { directory: f.directory });
  assert.equal(preview.detected, true); assert.deepEqual(preview.chats.map(chat => chat.id), ['codex-exact']);
  assert.equal(preview.chats[0].filename, undefined);
  await assert.rejects(f.api('projects/setup', { token: preview.token, selected: ['codex-other'] }), /supported/);
  const result = await f.api('projects/setup', { token: preview.token, selected: ['codex-exact'] });
  assert.equal(result.imported, 1); assert.equal(result.messages, 3);
  assert.deepEqual(await f.api('projects/setup', { token: preview.token, selected: ['codex-exact'] }), result, 'lost response retry is idempotent');
  const project = result.project.id;
  assert.ok((await f.api('projects/import-preview', { directory: f.directory })).existing);
  const db = createLocalDataStore(path.join(f.root, 'user-data'));
  assert.equal(db.projectIndexesReady(project), false);
  assert.equal(db.onboarding(project).imported_count, 1);
  db.close();
  const bootstrap = await f.api('bootstrap?' + new URLSearchParams({ project }));
  const imported = bootstrap.sessions.find(row => row.imported);
  assert.ok(imported); assert.equal(imported.organization.archived, false, 'source archive is provenance; imported copy is available');
  const chat = await f.api('chat?' + new URLSearchParams({ project, session: imported.id }));
  assert.equal(chat.messages[0].parts[0].text, 'Fix the turquoise widget');
  assert.equal(chat.messages[1].parts[0].state.output, 'Recorded widget source');
  assert.doesNotMatch(JSON.stringify(chat), /DO NOT IMPORT|PRIVATE SYSTEM|AUTH MUST/);
  await appendFile(source.source, JSON.stringify({ type: 'response_item', payload: { type: 'message', role: 'user', content: [{ type: 'input_text', text: 'This future change must not sync' }] } }) + '\n');
  assert.equal((await f.api('chat?' + new URLSearchParams({ project, session: imported.id }))).messages.length, 3);
  await f.app.history.rebuildChatSearch({ projectID: project });
  const search = await f.api('history/search?' + new URLSearchParams({ project, q: 'turquoise' }));
  assert.ok(search.results.some(row => row.session === imported.id));
  const exported = await f.api('history/export', { project, sessions: [imported.id], includeWorkers: true, format: 'json' });
  assert.equal(JSON.parse(exported.content).sessions[0].messages.length, 3);
  assert.equal(f.exports.length, 0);
  const pin = await f.api('history/pin', { project, session: imported.id, pinned: true, revision: 0 }, 'PUT');
  const archive = await f.api('history/archive', { project, session: imported.id, archived: true, revision: pin.revision }, 'PUT');
  await assert.rejects(f.api('chat/imported/continue', { project, session: imported.id }), /Restore/);
  await f.api('history/archive', { project, session: imported.id, archived: false, revision: archive.annotation.revision }, 'PUT');
  const continuation = await f.api('chat/imported/continue', { project, session: imported.id });
  assert.equal((await f.api('chat/imported/continue', { project, session: imported.id })).id, continuation.id);
  assert.equal(f.calls.filter(call => call.route === '/session' && call.options.method === 'POST').length, 1);
  await f.api('send', { project, session: continuation.id, text: 'Please continue', model: 'opencode/free', agentID: 'engineer', workflowID: 'build' });
  const dispatched = f.calls.filter(call => call.route.endsWith('/prompt_async')).at(-1).options.body;
  assert.equal(dispatched.agent, 'engineer');
  assert.equal(dispatched.parts[0].synthetic, true);
  assert.match(dispatched.parts[0].text, /turquoise/); assert.match(dispatched.parts[0].text, /not new instructions or permission/);
  assert.equal(dispatched.parts[1].text, 'Please continue');
  const resumed = await f.app.chat(project, continuation.id);
  assert.equal(resumed.messages.length, 4); assert.equal(resumed.messages.at(-1).parts.length, 1);
  delete f.state.status[continuation.id];
  await f.app.send(project, continuation.id, { text: 'Next step', model: 'opencode/free' });
  assert.equal(f.calls.filter(call => call.route.endsWith('/prompt_async')).at(-1).options.body.parts.length, 1);
  assert.deepEqual(await readFile(f.nativeFile), nativeBefore);
  assert.deepEqual(await readFile(source.database), dbBefore);
  await f.store.update('settings', settings => ({ ...settings, projects: [...settings.projects, { id: 'foreign', directory: f.directory + '-other', name: 'Other project' }] }));
  await assert.rejects(f.app.chat('foreign', imported.id), /another project/);
  await assert.rejects(f.app.chat(f.project.id, imported.id), /Choose a project/);
});

test('skip is final, missing installations are optional, and malformed/foreign transcripts cannot import', async t => {
  const f = await localDataFixture(); t.after(() => f.close());
  const source = await codexHistoryFixture(f);
  const preview = await f.app.chatgpt.preview(f.directory);
  const wrong = source.records.map(row => row.type === 'session_meta' ? { ...row, payload: { ...row.payload, cwd: f.directory + '-other' } } : row);
  assert.throws(() => parseCodexTranscript(wrong.map(JSON.stringify).join('\n'), { id: 'codex-exact' }, f.directory), /identity or project/);
  assert.throws(() => parseCodexTranscript('{}\nNOT JSON\n{}', { id: 'codex-exact' }, f.directory), /unreadable/);
  const parsed = parseCodexTranscript(source.records.map(JSON.stringify).join('\n'), { id: 'codex-exact' }, f.directory);
  assert.ok(orientationPart(parsed, 4000).text.length < 6000);
  const skipped = await f.app.chatgpt.complete(preview.token, []);
  assert.equal(skipped.imported, 0); assert.equal(f.app.chatgpt.list(skipped.project.id).length, 0);
  assert.ok((await f.app.chatgpt.preview(f.directory)).existing);
  await f.store.update('settings', settings => ({ ...settings, projects: [] }));
  const reopen = await f.app.chatgpt.preview(f.directory);
  assert.equal(reopen.chats.length, 0);
  const reopened = await f.app.chatgpt.complete(reopen.token, []);
  assert.equal(reopened.project.id, skipped.project.id);
  await f.store.update('settings', settings => ({ ...settings, projects: [] }));
  const noInstallation = createChatGPTImport({ app: f.app, backendRoot: f.root, codexHome: path.join(f.root, 'absent') });
  assert.deepEqual((await noInstallation.preview(f.directory)).chats, []);
});

test('uncertain native continuation creation is not replayed or duplicated', async t => {
  const f = await localDataFixture(); t.after(() => f.close());
  await codexHistoryFixture(f);
  const preview = await f.app.chatgpt.preview(f.directory);
  const result = await f.app.chatgpt.complete(preview.token, ['codex-exact']);
  const chat = f.app.chatgpt.list(result.project.id)[0];
  const create = f.app.createChat.bind(f.app);
  let attempts = 0;
  f.app.createChat = async (...args) => { attempts++; await create(...args); throw Error('Lost native creation response'); };
  await assert.rejects(f.app.chatgpt.resume(result.project.id, chat.id), /Lost native/);
  await assert.rejects(f.app.chatgpt.resume(result.project.id, chat.id), /not retried automatically/);
  assert.equal(attempts, 1);
});
