import assert from 'node:assert/strict';
import { localDataFixture } from './fixtures/local-data-app.mjs';
import { test, expect } from './support/browser-test.mjs';

test('a goal continues visibly while an independent worker stays busy', { tag: ['@app', '@chat'] }, async ({ appBrowser, own }) => {
  const f = await own(localDataFixture({ timers: false }));
  const g = await f.goals.create(f.project.id, { id: 'parallel_goal_browser_01', objective: 'Continue useful parent work', settings: { model: 'opencode/free' } });
  await f.goals.start(f.project.id, g.id); await f.sender.tick();
  const user = f.state.messages[g.session][0];
  const assistant = { info: { id: 'parallel_checkpoint_reply', role: 'assistant', parentID: user.info.id,
    agent: 'engineer', providerID: 'opencode', modelID: 'free', finish: 'stop', time: { created: Date.now(), completed: Date.now() } }, parts: [{ type: 'text', text: 'Checkpoint saved; continuing independent work.' }] };
  f.state.messages[g.session].push(assistant);
  f.state.sessions.push({ id: 'ses_parallel_goal_worker', parentID: g.session, directory: f.directory });
  f.state.status.ses_parallel_goal_worker = { type: 'busy' };
  await f.goals.checkpoint({ directory: f.directory, sessionID: g.session, messageID: assistant.info.id,
    outcome: 'continue', interpretation: 'Useful parent work remains', checkpoint: 'Partial work retained', reason: 'Continue independently', evidence: 'Worker still running' });
  delete f.state.status[g.session]; await f.sender.tick(); await f.goals.tick(); await f.sender.tick();
  const page = await appBrowser.newPage({ viewport: { width: 1280, height: 850 } });
  await page.goto(f.url);
  await page.getByRole('button', { name: 'Project settings', exact: true }).click();
  await page.getByRole('button', { name: 'Goals', exact: true }).click();
  await page.locator('.goal-row').getByRole('button', { name: 'Open chat', exact: true }).click();
  if (await page.getByRole('button', { name: /^Goals / }).getAttribute('aria-expanded') !== 'true')
    await page.getByRole('button', { name: /^Goals / }).click();
  await expect(page.getByRole('region', { name: 'Current goal' })).toContainText('Running');
  await expect(page.getByRole('button', { name: 'Stop goal', exact: true })).toBeVisible();
  assert.equal(f.calls.filter(c => c.route.endsWith('prompt_async')).length, 2);
  assert.equal(f.state.status.ses_parallel_goal_worker.type, 'busy');
});

test('goal forms stay consistent and contain large objectives, checkpoints and revisions', { tag: ['@app'] }, async ({ appBrowser, own }) => {
  const f = await own(localDataFixture({ timers: false }));
  const page = await appBrowser.newPage({ viewport: { width: 1280, height: 950 } });
  await page.goto(f.url);
  await page.getByRole('button', { name: 'Project settings', exact: true }).click();
  await page.getByRole('button', { name: 'Goals', exact: true }).click();
  await page.getByRole('button', { name: 'New goal', exact: true }).click();
  const create = page.getByRole('dialog', { name: 'New goal', exact: true });
  const objective = '# Large development plan\n' + 'Implement and verify this requirement.\n'.repeat(300) + 'x'.repeat(2000);
  await create.getByRole('textbox', { name: 'Goal title', exact: true }).fill('Large development plan');
  await create.getByRole('textbox', { name: 'Objective', exact: true }).fill(objective);
  for (const name of ['Agent', 'Parent model', 'Reasoning', 'Delegation', 'Worker models']) {
    await expect(create.getByRole('combobox', { name, exact: true })).toBeVisible();
  }
  const objectiveBox = await create.getByRole('textbox', { name: 'Objective', exact: true }).boundingBox();
  const delegation = create.getByRole('combobox', { name: 'Delegation', exact: true });
  await expect(delegation.locator('option')).toHaveText(['Agent decides', 'Encourage delegation', 'No delegation']);
  await delegation.selectOption({ label: 'Encourage delegation' });
  assert.ok(objectiveBox.height <= 260);
  assert.ok(await create.getByRole('textbox', { name: 'Objective', exact: true }).evaluate(el => el.scrollHeight > el.clientHeight));
  const formLabels = await create.locator('.field > span').allTextContents();
  await page.screenshot({ path: 'artifacts/goals-add-desktop.png' });
  await create.getByRole('button', { name: 'Save goal', exact: true }).click();
  const card = page.getByRole('region', { name: 'Goal: Large development plan', exact: true });
  await expect(card).toBeVisible();
  const saved = (await f.goals.list(f.project.id))[0];
  assert.equal(saved.title, 'Large development plan');
  assert.equal(saved.objective, objective);
  assert.equal(saved.settings.preferences.delegation, 'encouraged');
  assert.equal(f.state.sessions.find(s => s.id === saved.session).title, saved.title);
  assert.equal(f.calls.filter(c => c.route.endsWith('prompt_async')).length, 0);
  for (const name of ['Open chat', 'Start', 'Edit goal', 'Archive']) await expect(card.getByRole('button', { name, exact: true })).toBeVisible();
  const boxes = await card.locator('.goal-actions button').evaluateAll(els => els.map(el => ({ top: el.getBoundingClientRect().top, height: el.getBoundingClientRect().height })));
  assert.ok(boxes.every(b => b.top === boxes[0].top && b.height === boxes[0].height));
  await card.getByRole('button', { name: 'Edit goal', exact: true }).click();
  const edit = page.getByRole('dialog', { name: 'Edit goal', exact: true });
  await expect(edit.getByRole('combobox', { name: 'Delegation', exact: true })).toHaveValue('encouraged');
  assert.deepEqual(await edit.locator('.field > span').allTextContents(), formLabels);
  await expect(edit.getByRole('combobox', { name: 'Agent', exact: true })).toBeEnabled();
  await expect(edit.getByRole('textbox', { name: 'Objective', exact: true })).toHaveValue(objective);
  await edit.getByRole('textbox', { name: 'Objective', exact: true }).fill(objective + '\nAdditional acceptance check.');
  await edit.getByRole('button', { name: 'Save goal', exact: true }).click();
  await expect(edit).not.toBeVisible();
  // Exercise loading a 120 KB plan separately from Chromium's slow multiline insertText path.
  const loadedObjective = objective.repeat(9);
  await f.store.update('goals', d => ({ ...d, records: { ...d.records, [saved.id]: { ...d.records[saved.id], objective: loadedObjective, revisions: [{ revision: 1, objective: loadedObjective }], reason: 'Long status '.repeat(2000), checkpoint: { interpretation: loadedObjective, checkpoint: loadedObjective, evidence: 'x'.repeat(10000) } } } }));
  await expect(card.getByText('Latest checkpoint and evidence', { exact: true })).toBeVisible();
  for (const width of [1280, 390]) {
    await page.setViewportSize({ width, height: 950 });
    await card.getByText('Latest checkpoint and evidence', { exact: true }).click();
    const evidence = card.getByRole('region', { name: 'Checkpoint and evidence', exact: true });
    assert.ok((await evidence.boundingBox()).height <= 220);
    assert.ok(await evidence.evaluate(el => el.scrollHeight > el.clientHeight && el.scrollWidth <= el.clientWidth + 1));
    assert.ok((await card.boundingBox()).height < page.viewportSize().height);
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await page.screenshot({ path: `artifacts/goals-long-card-${width}.png` });
    await card.getByText('Latest checkpoint and evidence', { exact: true }).click();
    await card.getByRole('button', { name: 'Edit goal', exact: true }).click();
    await expect(edit.getByRole('textbox', { name: 'Objective', exact: true })).toHaveValue(loadedObjective);
    await edit.getByText('Previous objective revisions', { exact: true }).click();
    const history = edit.getByRole('region', { name: 'Previous objective revisions', exact: true });
    assert.ok((await history.boundingBox()).height <= 220);
    assert.ok(await edit.evaluate(el => el.scrollWidth <= el.clientWidth + 1));
    const dialogBox = await edit.boundingBox();
    assert.ok(dialogBox.x >= 0 && dialogBox.x + dialogBox.width <= width && dialogBox.height <= 950);
    await edit.locator('.ef-dialog-body').evaluate(el => { el.scrollTop = 0; });
    await page.screenshot({ path: `artifacts/goals-edit-${width}.png` });
    await edit.getByRole('button', { name: 'Cancel', exact: true }).click();
  }
  await card.getByRole('button', { name: 'Open chat', exact: true }).click();
  if (await page.getByRole('button', { name: /^Goals / }).getAttribute('aria-expanded') !== 'true') await page.getByRole('button', { name: /^Goals / }).click();
  const header = page.getByRole('region', { name: 'Current goal', exact: true });
  await expect(header.locator('.goal-header-title')).toHaveText('Large development plan');
  assert.ok((await header.boundingBox()).height < 200);
  await expect(header.getByRole('button', { name: 'Start goal', exact: true })).toBeVisible();
  await expect(page.getByRole('region', { name: 'Goal objective', exact: true })).not.toBeVisible();
  await expect(header).not.toContainText('Implement and verify this requirement.');
  await page.getByRole('button', { name: 'Hide goal', exact: true }).click();
  await expect(header).toHaveCount(0);
  await page.getByRole('button', { name: 'Show goal', exact: true }).click();
  await expect(header).toBeVisible();
  await page.screenshot({ path: 'artifacts/goals-long-chat-mobile.png' });
});

test('project goals save one chat, steer revisions, stop workers, and preserve mobile navigation', { tag: ['@app', '@chat'] }, async ({ appBrowser, own }) => {
  const f = await own(localDataFixture());
  const page = await appBrowser.newPage({ viewport: { width: 1280, height: 850 } });
  await page.goto(f.url);
  await page.getByRole('button', { name: 'Project settings', exact: true }).click();
  await page.getByRole('button', { name: 'Goals', exact: true }).click();
  await page.getByRole('button', { name: 'New goal', exact: true }).click();
  const dialog = page.getByRole('dialog', { name: 'New goal', exact: true });
  await dialog.getByRole('textbox', { name: 'Objective', exact: true }).fill('Verify the project goal experience');
  await dialog.getByRole('button', { name: 'Save goal', exact: true }).click();
  const card = page.locator('.goal-row');
  await expect(card.getByRole('status')).toHaveText('Ready');
  assert.equal(f.calls.filter(c => c.route.endsWith('prompt_async')).length, 0);
  const saved = (await f.goals.list(f.project.id))[0];
  await card.getByRole('button', { name: 'Open chat', exact: true }).click();
  if (await page.getByRole('button', { name: /^Goals / }).getAttribute('aria-expanded') !== 'true') await page.getByRole('button', { name: /^Goals / }).click();
  await expect(page.getByRole('region', { name: 'Current goal' })).toContainText('Ready');
  assert.equal(f.calls.filter(c => c.route.endsWith('prompt_async')).length, 0);
  await page.getByRole('button', { name: 'Manage goal', exact: true }).click();
  await card.getByRole('button', { name: 'Start', exact: true }).click();
  await expect(card.getByRole('status')).toHaveText('Running');
  await expect.poll(() => f.calls.filter(c => c.route.endsWith('prompt_async')).length).toBe(1);
  await expect(card.getByText('More', { exact: true })).toHaveCount(0);
  await card.getByRole('button', { name: 'Edit goal', exact: true }).click();
  const edit = page.getByRole('dialog', { name: 'Edit goal', exact: true });
  await expect(edit.getByRole('combobox', { name: 'Agent', exact: true })).toBeDisabled();
  await expect(edit.getByRole('combobox', { name: 'Agent', exact: true })).toBeVisible();
  await edit.getByRole('textbox', { name: 'Goal title', exact: true }).fill('Goal experience');
  await edit.getByRole('textbox', { name: 'Objective', exact: true }).fill('Verify the project goal experience including narrow layouts');
  const savedRevision = page.waitForResponse(response => response.url().endsWith('/api/goals') && response.request().method() === 'PUT');
  await edit.getByRole('button', { name: 'Save goal', exact: true }).click();
  const revisionResponse = await savedRevision;
  expect(revisionResponse.ok(), await revisionResponse.text()).toBe(true);
  await expect(edit).not.toBeVisible();
  await expect.poll(() => f.state.messages[saved.session]?.length ?? 0).toBe(2);
  assert.equal((await f.goals.list(f.project.id))[0].session, saved.session);
  assert.equal(f.calls.filter(c => c.route.endsWith('/abort')).length, 0);
  await card.getByRole('button', { name: 'Open chat', exact: true }).click();
  if (await page.getByRole('button', { name: /^Goals / }).getAttribute('aria-expanded') !== 'true') await page.getByRole('button', { name: /^Goals / }).click();
  await expect(page.locator('.goal-header-title')).toHaveText('Goal experience');
  await expect(page.locator('.goal-header')).not.toContainText('Verify the project goal experience including narrow layouts');
  const internalActivity = page.locator('.chat-transcript .message.internal');
  await expect(internalActivity).toHaveCount(1);
  const goalHandoff = internalActivity.locator('details.handoff-card');
  await expect(goalHandoff).not.toHaveAttribute('open');
  await expect(goalHandoff.locator('summary')).toContainText('Steer request');
  await expect(page.getByRole('button', { name: 'Open agents for turn 1', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Hide goal', exact: true }).click();
  await expect(page.getByRole('region', { name: 'Current goal', exact: true })).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Show goal', exact: true })).toBeVisible();
  assert.equal((await f.goals.list(f.project.id))[0].status, 'running');
  assert.equal(f.calls.filter(c => c.route.endsWith('/abort')).length, 0);
  await page.getByRole('button', { name: 'Show goal', exact: true }).click();
  await expect(page.locator('.goal-header-title')).toHaveText('Goal experience');
  let releaseStop, stopCalls = 0;
  const stopGate = new Promise(resolve => { releaseStop = resolve; });
  await page.route('**/api/goals/action', async route => {
    if (route.request().postDataJSON()?.action !== 'stop') return route.continue();
    stopCalls++; await stopGate; await route.continue();
  });
  const stoppedGoal = page.waitForResponse(response => response.url().endsWith('/api/goals/action') && response.request().postDataJSON()?.action === 'stop');
  await page.getByRole('button', { name: 'Stop goal', exact: true }).click();
  const stopping = page.getByRole('button', { name: 'Stopping…', exact: true });
  await expect(stopping).toBeDisabled();
  await stopping.evaluate(el => el.click());
  await expect.poll(() => stopCalls).toBe(1);
  releaseStop();
  const stopResponse = await stoppedGoal;
  expect(stopResponse.ok(), await stopResponse.text()).toBe(true);
  await expect(page.locator('.goal-header')).toContainText('Paused');
  await page.getByRole('button', { name: 'Manage goal', exact: true }).click();
  await expect(card.getByRole('status')).toHaveText('Paused');
  await page.screenshot({ path: 'artifacts/goals-desktop.png' });
  await page.setViewportSize({ width: 390, height: 844 });
  const navigation = page.locator('#workspace-navigation');
  await navigation.getByRole('button', { name: 'Project settings', exact: true }).click();
  if (await navigation.getByRole('button', { name: 'Goals', exact: true }).isVisible() === false) await navigation.getByRole('button', { name: 'Project settings', exact: true }).click();
  await navigation.getByRole('button', { name: 'Goals', exact: true }).click();
  await expect(navigation.locator('.nav-card-trigger[aria-expanded="true"]')).toHaveCount(0);
  await card.getByRole('button', { name: 'Open chat', exact: true }).click();
  if (await page.getByRole('button', { name: /^Goals / }).getAttribute('aria-expanded') !== 'true') await page.getByRole('button', { name: /^Goals / }).click();
  await expect(page.locator('.goal-header')).toBeVisible();
  await expect(navigation.locator('.nav-card-trigger[aria-expanded="true"]')).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Stop response', exact: true })).toHaveCount(0);
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.screenshot({ path: 'artifacts/goals-mobile.png' });
  await page.getByRole('button', { name: 'Manage goal', exact: true }).click();
  await card.getByRole('button', { name: 'Archive', exact: true }).click();
  await expect(card).not.toBeVisible();
  await page.getByRole('checkbox', { name: 'Show archived goals' }).check();
  await expect(card).toContainText('Archived');
  assert.ok(f.state.sessions.some(s => s.id === saved.session));
});
