import { readStateText as readFile } from '../backend/tools/runtime/state-database.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import { mkdtemp, rm } from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import { startServer } from '../server/http.mjs';
import { createRemoteAccess } from '../server/remote-access.mjs';
import { localLanAddresses } from '../server/lan.mjs';
import { savedWebPort, rememberWebPort } from '../server/web-port.mjs';

export async function unusedPort(host) {
  const server = http.createServer();
  await new Promise((resolve, reject) => { server.once('error', reject); server.listen(0, host, resolve); });
  const port = server.address().port;
  await new Promise(resolve => server.close(resolve));
  return port;
}
// A restarted listener needs a fresh transport. Do not reuse undici's socket
// pool from the killed server when testing durable device credentials.
const headers = { 'X-Freelancer-Client': 'webpage', 'Content-Type': 'application/json', Connection: 'close' };
const call = (url, route, body, method = body ? 'POST' : 'GET', extra = {}) => fetch(`${url}/api/${route}`, { method, headers: { ...headers, ...extra }, ...(body ? { body: JSON.stringify(body) } : {}) });

test('remembered devices survive restart on a fixed port; pairing, revocation and local controls stay bounded', async t => {
  const host = localLanAddresses()[0];
  if (!host) return t.skip('No private network adapter');
  const root = await mkdtemp(path.join(os.tmpdir(), 'freelancer-remote-'));
  const file = path.join(root, 'remote.json');
  let now = Date.now(), runtime;
  const application = { bootstrap: async () => ({ ready: true }), events: async function* (_p, signal) {
    yield 'data: ready\n\n';
    await new Promise(resolve => signal.addEventListener('abort', resolve, { once: true }));
  } };
  const start = async () => startServer({ application, remoteAccess: await createRemoteAccess({ file, now: () => now }) });
  t.after(async () => { await runtime?.close(); await rm(root, { recursive: true, force: true }); });
  runtime = await start();
  const port = await unusedPort(host);
  const options = { enabled: true, host, port, trustDays: 90 };
  assert.equal((await call(runtime.url, 'remote-access', options, 'PUT', { Origin: 'http://foreign.example' })).status, 403);
  assert.equal((await call(runtime.url, 'remote-access', { ...options, host: '8.8.8.8' }, 'PUT')).status, 400);
  assert.equal((await call(runtime.url, 'remote-access', { ...options, port: 0 }, 'PUT')).status, 400);
  assert.equal((await call(runtime.url, 'remote-access', options, 'PUT')).status, 200);
  const address = runtime.lanUrl;
  assert.equal(address, `http://${host}:${port}`);
  assert.equal((await call(address, 'bootstrap')).status, 403);
  assert.equal((await call(address, 'events?project=p')).status, 403);
  assert.equal((await call(address, 'bootstrap', undefined, 'GET', { Host: 'foreign.example' })).status, 403);
  const pairing = await (await call(runtime.url, 'remote-access/pairing', {})).json();
  assert.equal(Buffer.from(pairing.qr, 'base64').subarray(1, 4).toString(), 'PNG');
  const token = new URLSearchParams(new URL(pairing.url).hash.slice(1)).get('pair');
  const badOrigin = await call(address, 'access/pair', { token }, 'POST', { Origin: 'https://foreign.example' });
  assert.equal(badOrigin.status, 403);
  const paired = await call(address, 'access/pair', { token, name: 'My phone' });
  assert.equal(paired.status, 200);
  const setCookie = paired.headers.get('set-cookie');
  assert.match(setCookie, /HttpOnly; SameSite=Strict; Path=\/api; Max-Age=7776000/);
  const cookie = setCookie.split(';')[0];
  assert.equal((await call(address, 'access/pair', { token })).status, 403, 'one-time pairing');
  const authorized = { Cookie: cookie, Origin: address };
  assert.equal((await call(address, 'bootstrap', undefined, 'GET', authorized)).status, 200);
  assert.equal((await call(address, 'bootstrap', undefined, 'GET', { ...authorized, 'Sec-Fetch-Site': 'cross-site' })).status, 403);
  assert.equal((await call(address, 'remote-access', undefined, 'GET', authorized)).status, 403);
  assert.equal((await call(address, 'git/agent', {}, 'POST', authorized)).status, 403);
  const saved = await readFile(file, 'utf8');
  assert.ok(!saved.includes(token) && !saved.includes(cookie.split('=')[1]), 'no plaintext credentials on disk');
  const publicStatus = await (await call(runtime.url, 'remote-access')).json();
  assert.equal(publicStatus.devices[0].digest, undefined);
  const device = publicStatus.devices[0].id;
  await runtime.close(); runtime = await start();
  assert.equal(runtime.lanUrl, address, 'fixed address across restart');
  assert.equal((await call(address, 'bootstrap', undefined, 'GET', authorized)).status, 200, 'remembered credential survives restart');
  const stream = await call(address, 'events?project=p', undefined, 'GET', authorized);
  assert.equal(stream.status, 200);
  const reader = stream.body.getReader(); await reader.read();
  const ended = reader.read().then(v => v.done, () => true);
  assert.equal((await call(runtime.url, 'remote-access/devices', { id: device }, 'DELETE')).status, 200);
  assert.equal(await ended, true, 'revocation disconnects active event streams');
  assert.equal((await call(address, 'bootstrap', undefined, 'GET', authorized)).status, 403);
  const expiring = await (await call(runtime.url, 'remote-access/pairing', {})).json();
  now += 300001;
  assert.equal((await call(address, 'access/pair', { token: new URLSearchParams(new URL(expiring.url).hash.slice(1)).get('pair') })).status, 403);
  const fresh = await (await call(runtime.url, 'remote-access/pairing', {})).json();
  const login = await call(address, 'access/pair', { token: new URLSearchParams(new URL(fresh.url).hash.slice(1)).get('pair') });
  const freshCookie = login.headers.get('set-cookie').split(';')[0];
  await call(runtime.url, 'remote-access', { ...options, enabled: false }, 'PUT');
  assert.equal(runtime.lanUrl, undefined);
  await call(runtime.url, 'remote-access', options, 'PUT');
  assert.equal((await call(address, 'bootstrap', undefined, 'GET', { Cookie: freshCookie })).status, 200, 'disable retains remembered devices');
  now += 90 * 86400000 + 1;
  assert.equal((await call(address, 'bootstrap', undefined, 'GET', { Cookie: freshCookie })).status, 403, 'trust expires');
  const blocker = http.createServer();
  await new Promise(resolve => blocker.listen(0, host, resolve));
  t.after(() => new Promise(resolve => blocker.close(resolve)));
  const conflict = await call(runtime.url, 'remote-access', { ...options, port: blocker.address().port }, 'PUT');
  assert.equal(conflict.status, 400);
  assert.match((await conflict.json()).error, /already in use/);
  assert.equal(runtime.lanUrl, address, 'old listener survives failed change');
  assert.equal(JSON.parse(await readFile(file)).port, port);
  await runtime.close();
  const inaccessible = await createRemoteAccess({ file, addresses: () => [] });
  runtime = await startServer({ application, remoteAccess: inaccessible });
  assert.equal(inaccessible.status().enabled, true);
  assert.equal(inaccessible.status().active, false);
  assert.match(inaccessible.status().error, /available private/);
  assert.equal((await call(runtime.url, 'bootstrap')).status, 200, 'missing adapter does not block desktop');
});

test('desktop port is saved and validated without an ephemeral fallback', async t => {
  const root = await mkdtemp(path.join(os.tmpdir(), 'freelancer-port-'));
  t.after(() => rm(root, { recursive: true, force: true }));
  const file = path.join(root, 'port.json');
  assert.equal(await savedWebPort(file), 58633);
  await rememberWebPort(file, 58123);
  assert.equal(await savedWebPort(file), 58123);
  assert.equal(await savedWebPort(file, '58124'), 58124);
  await assert.rejects(savedWebPort(file, '0'));
});
