import assert from 'node:assert/strict';
import http from 'node:http';
import { mkdir } from 'node:fs/promises';
import { localLanAddresses } from '../server/lan.mjs';
import { localDataFixture } from './fixtures/local-data-app.mjs';
import { test, expect } from './support/browser-test.mjs';

test('network-access', { tag: ['@app'] }, async ({ appBrowser: browser, own }) => {
  const host = localLanAddresses()[0];
  if (!host) throw Error('LAN browser verification requires a private IPv4 network adapter.');
  const reservation = http.createServer();
  await new Promise(resolve => reservation.listen(0, host, resolve));
  const port = reservation.address().port;
  await new Promise(resolve => reservation.close(resolve));
  const f = await own(localDataFixture());
  f.state.messages.ses_history = [{ info: { id: 'phone-user', role: 'user' }, parts: [{ type: 'text', text: 'Phone LAN transcript' }] }];
  const desktop = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  await desktop.goto(f.url);
  await desktop.getByRole('button', { name: 'Application settings', exact: true }).click();
  await expect(desktop.locator('.settings-nav-section')).toHaveCount(0);
  await expect(desktop.locator('.settings-drawer-links:not([hidden]) button').first().locator('svg')).toBeVisible();
  await desktop.getByRole('button', { name: 'Remote access', exact: true }).click();
  await expect(desktop.getByRole('heading', { name: 'Remote access', exact: true })).toBeVisible();
  await desktop.getByLabel('Enable private-network access').check();
  await desktop.getByLabel('Network address').selectOption(host);
  await desktop.getByLabel('Port', { exact: true }).fill(String(port));
  await desktop.getByRole('button', { name: 'Save connection' }).click();
  await expect(desktop.getByText('Available on your network', { exact: true })).toBeVisible();
  const response = desktop.waitForResponse(r => r.url().endsWith('/api/remote-access/pairing') && r.request().method() === 'POST');
  await desktop.getByRole('button', { name: 'Show QR code' }).click();
  const pairing = await (await response).json();
  await expect(desktop.getByRole('img', { name: 'Scan to pair this device with Freelancer' })).toBeVisible();
  await mkdir('artifacts/remote-access', { recursive: true });
  await desktop.screenshot({ path: 'artifacts/remote-access/desktop.png', fullPage: true });
  const phoneContext = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
  let phone = await phoneContext.newPage();
  await phone.goto(pairing.url);
  await expect(phone.getByRole('heading', { name: 'Remember this device' })).toBeVisible();
  assert.equal(await phone.evaluate(() => location.hash), '', 'pairing code removed from history');
  await phone.getByLabel('Device name').fill('Test phone');
  await phone.screenshot({ path: 'artifacts/remote-access/phone.png' });
  await phone.getByRole('button', { name: 'Remember this device', exact: true }).click();
  await phone.getByRole('button', { name: 'Chats', exact: true }).click();
  await phone.locator('.nav-chat-select').filter({ hasText: 'Important conversation' }).click();
  await expect(phone.getByText('Phone LAN transcript', { exact: true })).toBeVisible();
  const cookies = await phoneContext.cookies();
  assert.ok(cookies.some(c => c.name.startsWith('freelancer_device_') && c.httpOnly && c.sameSite === 'Strict' && c.expires > Date.now() / 1000));
  assert.equal(await phone.evaluate(() => document.cookie.includes('freelancer_device_')), false);
  await expect(desktop.getByText('Test phone', { exact: true })).toBeVisible();
  await phone.close(); phone = await phoneContext.newPage();
  await phone.goto(new URL(pairing.url).origin);
  await expect(phone.getByRole('button', { name: 'Chats', exact: true })).toBeVisible();
  await desktop.reload();
  await desktop.getByRole('button', { name: 'Application settings', exact: true }).click();
  await desktop.getByRole('button', { name: 'Remote access', exact: true }).click();
  await expect(desktop.getByLabel('Port', { exact: true })).toHaveValue(String(port));
  await expect(desktop.getByLabel('Enable private-network access')).toBeChecked();
  const stranger = await browser.newPage({ viewport: { width: 390, height: 844 } });
  await stranger.goto(new URL(pairing.url).origin);
  await expect(stranger.getByRole('heading', { name: 'Connect to Freelancer' })).toBeVisible();
  await desktop.getByRole('button', { name: 'Remove Test phone' }).click();
  await expect(desktop.getByText('No devices remembered yet.', { exact: true })).toBeVisible();
  await phone.reload();
  await expect(phone.getByRole('heading', { name: 'Connect to Freelancer' })).toBeVisible();
  await desktop.getByLabel('Enable private-network access').uncheck();
  await desktop.getByRole('button', { name: 'Save connection' }).click();
  await expect(desktop.getByText('Private-network access is off', { exact: true })).toBeVisible();
  await browser.close();
});
