import { mixColor, onColor, readableColor } from './color.mjs';

// One small application-owned palette catalog, not an editable style engine.
// A palette's mode also drives the browser's built-in widgets.
const definitions = [
  { id: 'light', name: 'Light', mode: 'light', description: 'Fresh paper and soft greens.',
    bg: '#f8f9f6', paper: '#ffffff', sidebar: '#eef1ec', text: '#252d2a', muted: '#68726b', line: '#e1e7df', accent: '#426b4c', tint: '#e4eddf', hover: '#e8ede5' },
  { id: 'dark', name: 'Dark', mode: 'dark', description: 'Charcoal with a calm green accent.',
    bg: '#171c19', paper: '#1e2520', sidebar: '#121814', text: '#e4ebe2', muted: '#9aa99b', line: '#303c33', accent: '#a5c695', tint: '#293c2a', hover: '#263127' },
  { id: 'sandstone', name: 'Sandstone', mode: 'light', description: 'Warm ivory, sand, and terracotta.',
    bg: '#faf6ee', paper: '#fffdf8', sidebar: '#f1e9dc', text: '#352c26', muted: '#756758', line: '#e3d7c5', accent: '#9b4b32', tint: '#f3e3d5', hover: '#eee3d5' },
  { id: 'midnight', name: 'Midnight', mode: 'dark', description: 'Deep navy with clear blue highlights.',
    bg: '#101827', paper: '#172237', sidebar: '#0c1321', text: '#e4edf9', muted: '#a1b2cb', line: '#2c3e58', accent: '#85b9ff', tint: '#233854', hover: '#203149' },
];
function palette(definition) {
  const { id, name, mode, description, ...base } = definition;
  const surfaces = [base.bg, base.paper, base.sidebar, base.tint, base.hover];
  const accent = readableColor(base.accent, surfaces);
  const tokens = { ...base, accent,
    muted: readableColor(base.muted, surfaces),
    'accent-contrast': onColor(accent),
    'accent-hover': readableColor(mixColor(accent, mode === 'dark' ? '#ffffff' : '#000000', 0.08), surfaces),
    'border-strong': readableColor(base.muted, [base.paper, base.bg, base.sidebar], 3),
    focus: readableColor(base.accent, surfaces, 3),
    link: accent,
    'code-bg': base.sidebar, 'code-text': base.text,
    overlay: mode === 'dark' ? '#020711bb' : '#15201866',
    'overlay-strong': mode === 'dark' ? '#020711dd' : '#152018bb',
    shadow: mode === 'dark' ? '#00000066' : '#00000033',
    'shadow-soft': mode === 'dark' ? '#00000033' : '#00000014',
  };
  for (const [role, color] of Object.entries({ success: '#22834a', danger: '#be3b36', warning: '#986000', info: '#2865b2' })) {
    const tint = mixColor(base.paper, color, mode === 'dark' ? 0.17 : 0.09);
    tokens[role + '-tint'] = tint;
    tokens[role] = readableColor(color, [...surfaces, tint]);
    tokens[role + '-contrast'] = onColor(tokens[role]);
  }
  return Object.freeze({ id, name, mode, description, tokens: Object.freeze(tokens) });
}
export const palettes = Object.freeze(definitions.map(palette));
export const isTheme = value => palettes.some(p => p.id === value);
export const resolveTheme = value => isTheme(value) ? value : 'light';
export const themePalette = value => palettes.find(p => p.id === resolveTheme(value));
export const themeMode = value => themePalette(value).mode;
export const themeColors = Object.freeze(Object.fromEntries(palettes.map(p => [p.id, p.tokens.bg])));
export function themeStyle(value) {
  const p = themePalette(value);
  return Object.fromEntries(Object.entries(p.tokens).map(([key, color]) => ['--' + key, color]));
}
export function applyTheme(value, root = document.documentElement) {
  const p = themePalette(value);
  root.dataset.theme = p.id;
  root.style.backgroundColor = p.tokens.bg;
  root.style.colorScheme = p.mode;
  for (const [key, color] of Object.entries(themeStyle(p.id))) root.style.setProperty(key, color);
}
// Checked-in fallback CSS is generated from exactly these same tokens. It also
// makes Vite development and server-rendered fixtures independent of JavaScript.
export function paletteCSS() {
  return '/* Generated by scripts/palette-css.mjs. Edit domain/theme.mjs, not this file. */\n' + palettes.map(p =>
    `${p.id === 'light' ? ':root, ' : ''}:root[data-theme="${p.id}"] {\n  color-scheme: ${p.mode};\n` +
    Object.entries(themeStyle(p.id)).map(([key, color]) => `  ${key}: ${color};`).join('\n') + '\n}\n').join('\n');
}
